### ISSUE TITLE
Ubuntu 20.04 and ROS Noetic -> ImportError: No module named yaml

### ISSUE THREAD

**Issue by Zolubas** [appie-17/tello_driver#14]
Hi, I'm working on Ubuntu 20.04 and ROS Noetic. I want to install tello_driver but I get the following error message:

```
SUMMARY
========

PARAMETERS
 * /rosdistro: noetic
 * /rosversion: 1.16.0
 * /tello/tello_driver_node/camera_calibration: /home/user/roswor...
 * /tello/tello_driver_node/connect_timeout_sec: 10.0
 * /tello/tello_driver_node/local_cmd_client_port: 8890
 * /tello/tello_driver_node/local_vid_server_port: 6038
 * /tello/tello_driver_node/stream_h264_video: True
 * /tello/tello_driver_node/tello_cmd_server_port: 8889
 * /tello/tello_driver_node/tello_ip: 192.168.10.1

NODES
  /tello/
    image_compressed (image_transport/republish)
    tello_driver_node (tello_driver/tello_driver_node)

ROS_MASTER_URI=http://localhost:11311

process[tello/tello_driver_node-1]: started with pid [68052]
WARNING: Package name "turtle_controllers_A2B" does not follow the naming conventions. It should start with a lower case letter and only contain lower case letters, digits, underscores, and dashes.
process[tello/image_compressed-2]: started with pid [68053]
Traceback (most recent call last):
  File "/home/user/rosworskpaces/urubu/src/tello_driver/nodes/tello_driver_node", line 2, in <module>
    import rospy
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py", line 47, in <module>
    from std_msgs.msg import Header
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/__init__.py", line 1, in <module>
    from ._Bool import *
  File "/opt/ros/noetic/lib/python3/dist-packages/std_msgs/msg/_Bool.py", line 6, in <module>
    import genpy
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/__init__.py", line 34, in <module>
    from . message import Message, SerializationError, DeserializationError, MessageException, struct_I
  File "/opt/ros/noetic/lib/python3/dist-packages/genpy/message.py", line 50, in <module>
    import yaml
ImportError: No module named yaml
[tello/tello_driver_node-1] process has died [pid 68052, exit code 1, cmd /home/user/rosworskpaces/urubu/src/tello_driver/nodes/tello_driver_node __name:=tello_driver_node __log:=/home/user/.ros/log/68f837dc-3646-11ee-bd15-894ccdf7d5d8/tello-tello_driver_node-1.log].
log file: /home/user/.ros/log/68f837dc-3646-11ee-bd15-894ccdf7d5d8/tello-tello_driver_node-1*.log

```

I tried install the yaml using pip3 install pyyaml, pip install pyaml but the issue persists.

```
user@drone:~$ pip3 install pyyaml
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (5.3.1)
```

Does anyone know what the problem could be? Any help would be amazing. Thanks!

**Comment by jonaug88** [comment]
Have you changed "#!/usr/bin/env python2" to #!/usr/bin/env python3 at the top of your tello_driver_node?
