### ISSUE TITLE
No module named _internal.tello

### ISSUE THREAD

**Issue by droter** [appie-17/tello_driver#3]
Thanks for making this package.  Looks awesome!

I ran into this error starting the tello_node:

Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/tello_driver/tello_driver_node", line 17, in <module>
    from tellopy._internal import tello
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/tellopy/__init__.py", line 8, in <module>
    from tellopy._internal.tello import Tello
ImportError: No module named _internal.tello

**Comment by Marcuran** [comment]
Hi, 

I encounter the same problem, did you find a way to solve it?

**Comment by droter** [comment]
I switched to python3 and noetic.

**Comment by zcemycl** [comment]
same here. I am using kinetic ros. 
If I 'pip2 install tellopy', run 'python2 -m tellopy.examples.simple_takeoff'. It can takeoff. 
Once I 'sudo apt install ros-kinetic-tello-driver', that python script no longer works. If I run tello_node, it also gives me the importerror.

**Comment by zcemycl** [comment]
I solved this by installation from source.

**Comment by syediu** [comment]
@droter How did you move to **Noetic**? As far I know the latest release of `tello_driver` is for `ROS Melodic` with `Python2` and has not been released for `ROS Noetic` with `python3` support.

If you have maintained any repository, please link here so that others can take benefit from that. Thanks
